### ISSUE TITLE
拉取源码，用idea社区版本 打开后 无法编译，需要做什么配置吗？

### ISSUE THREAD

**Issue by SjAndy88** [dengzii/RemoveButterKnife#3]
![image](https://user-images.githubusercontent.com/5946178/123572205-5d2fa280-d7fe-11eb-82ab-d9989d192746.png)

新手，想针对自己的源码客制化下你的代码功能，但是拉下来后发现不太会配置这个。

**Comment by dengzii** [comment]
参考这个 [GenerateModuleFromTemplate#build](https://github.com/dengzii/GenerateModuleFromTemplate#build)

**Comment by SjAndy88** [comment]
> 参考这个 [GenerateModuleFromTemplate#build](https://github.com/dengzii/GenerateModuleFromTemplate#build)

Pressing the Ctrl + Alt + Shift + S to open Project Structure dialog, choose Project tab, change Project SDK to IntelliJ IDEA Community Edition IC-xxxx, then apply change.   

这个IntelliJ IDEA Community Edition IC-xxxx没有看到 应该是需要另外配置的吧

**Comment by dengzii** [comment]
要先导入, 你选择 `Project Structure > SDKs` 点加号, 有一个 `Add IntelliJ Platform xxx`, 然后你选择 IDEA 的安装路径就好了
