### ISSUE TITLE
代码调试

### ISSUE THREAD

**Issue by SjAndy88** [dengzii/RemoveButterKnife#4]
想问下这个调试是怎么操作啊。  
可以和AndroidStudio联调吗 
println("insertInvokeBindViewMethodStatement")  输出log信息在什么地方可以看到

**Comment by dengzii** [comment]
不能和AndroidStudio联调, 直接用 IDEA联调, 可以创建一个和ButterKnife一样的 包名,   然后创建一个类模拟一下注解
 
在 IDEA社区版配置好了直接运行, 会打开一个新的 IDEA, 插件就跑在上面, log 在控制台可以看到

**Comment by SjAndy88** [comment]
好的  我试试

**Comment by SjAndy88** [comment]
感谢，解决了一个大问题

**Comment by dengzii** [comment]
👏
